services:
  app:
    build:
      context: .
    container_name: express_app_marcelo
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app         
      - /usr/src/app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
